apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    spec:
      containers:
      - name: my-container
        image: battletoady/ml_in_prod_project:latest
      restartPolicy: Never